var conditions = [
  {
    cid: 1,
    Q1: "What is a cervicogenic headache?",
    A1a: "Cervicogenic headache is thought to be a referred pain from irritation to neck structures (joints and soft tissues) innervated by C1-3 spinal nerves.",
    Q2: "What are the common clinical features?",
    A2a: "Headache is one-sided without a side shift with pain in the neck, shoulder, or arm on the same side.",
    A2b: "Reduced neck range of motion.",
    A2c: "Pain is worse with suboptimal posture and movement of the head and neck.",
    Q3: "How to manage the cervicogenic headache?",
    A3a: "Treatment and management: reduce pain with manual therapy, massage therapy, acupuncture, cupping therapy, or electrotherapy.",
    A3b: "Exercises: range of motion, stretches, and strengthening exercises."
  },
  {
    cid: 2,
    Q1: "What caused neck pain?",
    A1a: "From incident (whiplash): might involve muscle strain, ligament sprain, or fracture.",
    A1b: "From overuse: might involve sustained postures from daily tasks (home or work) or poor sleep postures causing tissue overloading.",
    A1c: "Contributing factors (poor quality of sleep and bad mood, and so on) might amplify your pain experience.",
    Q2: "How to manage neck pain?",
    A2a: "For whiplash",
    A2ai: "Assessment: your physiotherapist will do thorough assessments based on guidelines.",
    A2aii: "Investigation: might require an X-ray for the neck depending on assessment findings.",
    A2aiii: "Treatment: relieve pain and associated symptoms with manual therapy.",
    A2aiv: "Exercises: improve muscle performance (strength and control) and address other impairments.",
    A2av: "Optimism: stay positive.",
    A2b: "For overuse",
    A2bi: "Treatment and management: relieve pain and associated symptoms with acupuncture, manual therapy, massage therapy, electrotherapy, cupping therapy, or taping.",
    A2bii: "Exercises: improve neck range of motion and muscle performance."
  },
  {
    cid: 3,
    Q1: "What structures are involved in shoulder pain?",
    A1a: "Rotator cuff related (tear/tendinopathy/bursitis)",
    A1b: "Joint related (frozen shoulder/labral tear/ACJ sprain)",
    Q2: "How to manage shoulder pain?",
    A2a: "Treatment and management:",
    A2ai: "Deload: avoid or modify activities that aggravate symptoms.",
    A2aii: "Taping: taping might be used to reduce pain and offload sensitive structures around the shoulder.",
    A2aiii: "Acupuncture: acupuncture might be used to release trigger points and provide short-term pain relief.",
    A2aiv: "Manual therapy: soft and deep tissue release, joint mobilization, or stretching might be used to reduce pain and muscle tightness, and improve range of motion.",
    A2av: "Shockwave therapy: reduce tissue tightness around shoulder",
    A2avi: "Electrotherapy: therapeutic ultrasound might be used to reduce pain and inflammation.",
    A2b: "Exercises:",
    A2bi: "Range of motion exercises: Range of motion exercises help to improve shoulder mobility and prevent stiffness.",
    A2bii: "Strengthening exercises: Strengthening exercises for rotator cuffs and muscles around the shoulder blade can improve shoulder biomechanics and reduce pain."
  },
  {
    cid: 4,
    Q1: "What caused mid back pain?",
    A1a: "Pain might be from irritation to intervertebral discs, rib articulations, Z joints, or paraspinals in mid-back region as a result of incident, repetitive movements, or sustained postures from daily tasks (home or work).",
    Q2: "How to manage mid back pain?",
    A2a: "Treatment and management: reduce pain and stiffness with manual therapy, massage therapy, or cupping therapy.",
    A2b: "Exercises: range of motion, stretches, and strengthening exercises."
  },
  {
    cid: 5,
    Q1: "What are the common conditions that cause elbow pain?",
    A1a: "Tennis elbow: it involves extensor muscles of the forearm. It is common in tennis players but not limited to other sports players (squash and badminton) or non-sport populations. The main reason for developing tennis elbow is overuse.",
    A1b: "Golfer’s elbow: it involves flexor muscles of the forearm. It is common in golf players but not limited to other sports players. The main reason for developing a golfer's elbow is overuse.",
    Q2: "How to manage elbow pain?",
    A2a: "Treatment and management:",
    A2ai: "Deload: avoid or modify activities that aggravate symptoms. Sometimes, elbow brace might be suggested to relieve symptoms.",
    A2aii: "Taping: taping might be used to reduce pain and offload sensitive structures around the elbow.",
    A2aiii: "Acupuncture: acupuncture might be used to release trigger points, reduce muscle tightness, and restore muscle function.",
    A2aiv: "Manual therapy: soft and deep tissue release, or joint mobilization might be used to reduce pain and improve range of motion.",
    A2av: "Shockwave therapy: promote tissue healing.",
    A2avi: "Electrotherapy: therapeutic ultrasound or interferential therapy might be used to reduce pain and inflammation.",
    A2b: "Exercises:",
    A2bi: "Range of motion exercises: Range of motion exercises help to improve elbow and wrist mobility and prevent stiffness.",
    A2bii: "Strengthening exercises: Strengthening exercises for upper limbs can improve muscle performance."
  },
  {
    cid: 6,
    Q1: "What caused low back pain?",
    A1a: "From incident: might involve muscle strain, ligament sprain, or fracture.",
    A1b: "From overuse: might involve repetitive movements or sustained postures from daily tasks (home or work) causing tissue overloading.",
    A1c: "Contributing factors (poor quality of sleep and bad mood, and so on) might amplify your pain experience.",
    Q2: "How to manage low back pain?",
    A2a: "Treatment and management: reduce pain with manual therapy, massage therapy, acupuncture, taping, cupping therapy, or electrotherapy.",
    A2b: "Exercises: range of motion, stretches, and strengthening exercises.",
    Q3: "What caused sciatica?",
    A3a: "Sciatica refers to pain and inflammation that affects the sciatic nerve, which travels from the lower back and down the leg. Irritation to sciatic nerve might be from bulging lumbar discs or tightness in the hip muscles such as piriformis (piriformis syndrome). Sciatic pain might be accompanied with pins and needles, tinglings, numbness, or weakness in the lower limb.",
    Q4: "How to manage sciatica?",
    A4a: "Treatment and management: reduce pain with manual therapy, massage therapy, acupuncture, cupping therapy, or electrotherapy.",
    A4b: "Exercises: range of motion, stretches, and strengthening exercises."
  },
  {
    cid: 7,
    Q1: "What structures are involved in pelvic girdle pain (PGP)?",
    A1a: "The structures that are commonly involved are sacroiliac joint, symphysis pubis and the surrounding ligaments and muscles.",
    Q2: "How to manage PGP?",
    A2a: "A biopsychosocial model will be used to guide treatment and management.",
    A2b: "Treatment and management: reduce pain with massage therapy, acupuncture, taping, cupping therapy, or electrotherapy.",
    A2c: "Exercises: stretches, strengthening, and relaxation exercises."
  },
  {
    cid: 8,
    Q1: "What are the common conditions that cause thumb pain?",
    A1a: "Mother’s thumb: also called De Quervain’s tenosynovitis affects the synovium of abductor pollicis longus and extensor pollicis brevis tendons. This results in pain, swelling, and inflammation.",
    Q2: "How to manage thumb pain?",
    example: "For mother’s thumb",
    A2a: "Treatment and management:",
    A2ai: "Deload: avoid or modify activities that aggravate symptoms. Sometimes, thumb brace might be suggested to relieve symptoms.",
    A2aii: "Taping: taping might be used to reduce pain and offload sensitive structures around the thumb.",
    A2aiii: "Acupuncture: acupuncture might be used to release trigger points, reduce muscle tightness, and restore muscle function.",
    A2aiv: "Shockwave therapy: promote tissue healing.",
    A2av: "Electrotherapy: therapeutic ultrasound or interferential therapy might be used to reduce pain and inflammation.",
    A2b: "Exercises:",
    A2bi: "Range of motion exercises: Range of motion exercises help to improve thumb and wrist mobility and prevent stiffness.",
    A2bii: "Strengthening exercises: Strengthening exercises for upper limbs can improve muscle performance."
  },
  {
    cid: 9,
    Q1: "What are the common conditions that cause wrist pain?",
    A1a: "Carpal tunnel syndrome: the median nerve is compressed as it passes through the carpal tunnel. This condition is characterized by burning wrist pain with numbness in the first three fingers.",
    Q2: "How to manage wrist pain?",
    example: "For carpal tunnel syndrome",
    A2a: "Treatment and management:",
    A2ai: "Splinting and taping: maintain wrist in neutral to avoid compression to the median nerve.",
    A2aii: "Electrotherapy: might be helpful to reduce pain, swelling, and inflammation.",
    A2b: "Exercises:",
    A2bi: "Nerve and tendon gliding exercises.",
    A2bii: "Median nerve sliding exercises."
  },
  {
    cid: 10,
    Q1: "What are the common conditions that cause hip pain?",
    A1a: "Hip osteoarthritis: degenerative condition that affects the hip joint. The cartilage that cushions the joint is worn down causing inflammation, pain, and stiffness.",
    Q2: "How to manage hip pain?",
    example: "For hip osteoarthritis",
    A2a: "Treatment and management:",
    A2ai: "Reduce pain with manual therapy and hydrotherapy.",
    A2aii: "Adopt healthy lifestyle.",
    A2b: "Exercises are key in managing hip osteoarthritis. These include hip range of motion, hip strengthening exercises (deep hip stabilizers, gluteus maximus and medius, lower limbs, and trunk), and balance and proprioception."
  },
  {
    cid: 11,
    Q1: "What caused posterior thigh pain?",
    A1a: "Type 1 hamstring strain: sprinting-related injury that involves high speed.",
    A1b: "Type 2 hamstring strain: stretch-related injury that is commonly seen in dancers and gymnasts.",
    Q2: "How to manage posterior thigh pain?",
    A2a: "PEACE & LOVE principle will be used to manage hamstring strain.",
    A2ai: "Protect hamstring by deloading.",
    A2aii: "Elevate the injured limb to reduce swelling.",
    A2aiii: "Avoid anti-inflammatory medications and ice.",
    A2aiv: "Compress with taping or bandages to reduce swelling.",
    A2av: "Educate the benefits of active approach to recovery.",
    A2avi: "Load with gentle movement and exercises.",
    A2avii: "Optimism: being optimistic.",
    A2aviii: "Vascularisation: aerobic and cardiovascular exercises.",
    A2aix: "Exercises to improve mobility, strength, and flexibility.",
    A2b: "In addition to acute soft tissue management described above, treatment (acupuncture, electrotherapy, massage therapy, or cupping therapy) and strengthening exercises should be commenced as soon as possible to enhance recovery."
  },
  {
    cid: 12,
    Q1: "What are the common conditions that cause knee pain?",
    A1a: "Knee osteoarthritis: often called “wear and tear” arthritis. People with knee osteoarthritis usually complain about pain and stiffness which might affect their mobility.",
    A1b: "Patellofemoral pain syndrome: The patellofemoral joint is the articulation between the patella and the femoral trochlea. Patellofemoral pain occurs when the patellofemoral joint is overloaded. Patellofemoral pain is often associated with activities that load the patellofemoral joint such as stair walking, squating, and running.",
    Q2: "How to manage knee pain?",
    example: "For knee osteoarthritis",
    A2a: "Treatment and management:",
    A2ai: "Reduce pain with manual therapy and hydrotherapy.",
    A2aii: "Adopt healthy lifestyle.",
    A2b: "Exercises are key in managing knee osteoarthritis. These include range of motion and strengthening exercises (quadriceps, hamstring, and gluteus).",
    example1: "For patellofemoral pain syndrome",
    A2a1: "Treatment and management:",
    A2a1i: "Reduce pain with manual therapy and taping.",
    A2b1: "Exercises are key in managing patellofemoral pain syndrome. These include range of motion exercises, strengthening exercises (quadriceps, hip muscles, lower limbs, and trunk muscles), and balance and coordination training."
  },
  {
    cid: 13,
    Q1: "What are the common conditions that cause posterior leg pain?",
    A1a: "Gastrocnemius and soleus strain: both are common causes of posterior leg pain. It occurs when the muscles are overstretched with speed.",
    Q2: "How to manage posterior leg pain?",
    A2a: "PEACE & LOVE principle will be used to manage calf strain.",
    A2ai: "Protect calf by deloading.",
    A2aii: "Elevate the injured limb to reduce swelling.",
    A2aiii: "Avoid anti-inflammatory medications and ice.",
    A2aiv: "Compress with taping or bandages to reduce swelling.",
    A2av: "Educate the benefits of active approach to recovery.",
    A2avi: "Load with gentle movement and exercises.",
    A2avii: "Optimism: being optimistic.",
    A2aviii: "Vascularisation: aerobic and cardiovascular exercises.",
    A2aix: "Exercises to improve mobility, strength, and flexibility.",
    A2b: "In addition to acute soft tissue management described above, treatment (acupuncture, electrotherapy, massage therapy, or cupping therapy) and strengthening exercises should be commenced as soon as possible to optimize tissue healing.",
    Q3: "What are the common conditions that cause medial leg pain?",
    A3a: "Medial tibial stress syndrome (shin splints): shin splints is a common cause of medial leg pain due to overuse. People with shin splints complain about diffuse pain along the medial aspect of the tibia. Flexor digitorum longus is thought to be the source of pain.",
    Q4: "How to manage medial leg pain?",
    A4a: "Treatment and management:",
    A4ai: "Deload: avoid or modify activities that aggravate symptoms. Sometimes, poor footwear might be one of the contributing factors to overloading muscles.",
    A4aii: "Taping: taping might be used to reduce pain and offload sensitive structures around the leg.",
    A4aiii: "Acupuncture: acupuncture might be used to release trigger points, reduce muscle tightness, and restore muscle function.",
    A4aiv: "Manual therapy: soft and deep tissue release, or joint mobilization might be used to reduce pain and improve range of motion.",
    A4av: "Electrotherapy: therapeutic ultrasound or interferential therapy might be used to reduce pain and inflammation.",
    A4b: "Exercises:",
    A4bi: "Range of motion exercises: Range of motion exercises help to improve ankle and foot mobility and prevent stiffness.",
    A4bii: "Strengthening exercises: Strengthening exercises for lower limbs can improve muscle performance."
  },
  {
    cid: 14,
    Q1: "What are the common conditions that cause achilles pain?",
    A1a: "Midportion and insertional achilles tendinopathy: achilles tendon is the combined tendon of gastrocnemius and soleus muscles. People with achilles tendinopathy complain about gradual onset of pain around mid-portion or at insertion. Achilles tendinopathy might occur in a single episode (reactive) or over a period of time (degenerative) as a result of the achilles tendon being overloaded.",
    Q2: "How to manage achilles pain",
    A2a: "Treatment and management:",
    A2ai: "Deload: avoid or modify activities that aggravate symptoms. Shoe inserts might be used to reduce pain and offload achilles tendon.",
    A2aii: "Acupuncture: acupuncture might be used to release trigger points, reduce muscle tightness, and restore muscle function.",
    A2aiii: "Manual therapy: soft and deep tissue release, or joint mobilization might be used to reduce pain and improve range of motion.",
    A2aiv: "Electrotherapy: therapeutic ultrasound or interferential therapy might be used to reduce pain and inflammation.",
    A2b: "Exercises:",
    A2bi: "Range of motion exercises: Range of motion exercises help to improve ankle mobility and prevent stiffness.",
    A2bii: "Strengthening exercises: Strengthening exercises (isometric, isotonic, plyometric) for lower limbs can improve muscle performance."
  },
  {
    cid: 15,
    Q1: "What are the common conditions that cause ankle pain?",
    A1a: "Ankle sprain: Ankle joint is stabilized with its specific bone arrangement and the surrounding ligaments. Ligaments are tough bands of tissue that support and hold joints together. When you overstretch or tear one of these ligaments, this results in a sprained ankle.",
    Q2: "How to manage ankle pain?",
    example: "For ankle sprain",
    A2a: "PEACE & LOVE principle will be used to manage an ankle sprain.",
    A2ai: "Protect ankle by deloading.",
    A2aii: "Elevate the injured limb to reduce swelling.",
    A2aiii: "Avoid anti-inflammatory medications and ice.",
    A2aiv: "Compress with taping or bandages to reduce swelling.",
    A2av: "Educate the benefits of active approach to recovery.",
    A2avi: "Load with gentle movement and exercises.",
    A2avii: "Optimism: being optimistic.",
    A2aviii: "Vascularisation: aerobic and cardiovascular exercises.",
    A2aix: "Exercises to improve mobility, strength, and proprioception.",
    A2b: "In addition to acute soft tissue management described above, treatment and exercises (range of motion, strengthening, and balance and proprioception exercises) should be commenced as soon as possible to optimize tissue healing."
  },
  {
    cid: 16,
    Q1: "What are the common conditions that cause foot pain?",
    A1a: "Plantar fasciitis: develops when the connective tissue (plantar fascia), which supports the arch of the foot, is irritated as a result of being overused, overstretched, or direct pressure.",
    Q2: "How to manage foot pain?",
    example: "Plantar fasciitis",
    A2a: "Treatment and management:",
    A2ai: "Deload: avoid or modify activities that aggravate symptoms. Sometimes, customized and prefabricated foot orthoses might be used to relieve symptoms.",
    A2aii: "Taping: low dye taping to support plantar fascia.",
    A2aiii: "Shockwave therapy: promote tissue healing.",
    A2aiv: "Acupuncture: reduce muscle tightness in lower limbs.",
    A2av: "Massage therapy: reduce tension in plantar fascia and proximal myofascial regions (calf/hamstrings/glutes).",
    A2avi: "Manual therapy: reduce joint stiffness around the foot.",
    A2b: "Exercises: stretches (plantar fascia/calf) and strengthening exercises (lower limbs and foot intrinsics)."
  }
];

export function getCondition(id) {
  return conditions.find(
    condition => condition.cid === id + 1
  );
}